spring:
  application:
    name: pract4_server
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/dealership
    username: admin
    password: admin
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5433/dealership
    user: admin
    password: admin
  rsocket:
    server:
      port: 7000
      transport: tcp

logging:
  level:
    org:
      flywaydb: debug
